development:
  adapter: postgresql
  database: inspire_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: inspire_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: inspire_production
  pool: 5
  timeout: 5000